kind: pipeline
type: kubernetes
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: registry.internal.hoffmeister.biz/diztortion/exim
      registry: registry.internal.hoffmeister.biz
      auto_tags: true
